export enum ModalType {
  ADD_EDIT_SCENARIO = "ADD_EDIT_SCENARIO",
  ADD_EDIT_AB_TEST = "ADD_EDIT_AB_TEST",
  VIEW_AB_TEST = "VIEW_AB_TEST",
  CONFIRM_CANCEL = "CONFIRM_CANCEL",
  CONFIRM_APPROVE = "CONFIRM_APPROVE",
}
