export const SELENIUM_TEST_IDS = {
  menu: {
    subListArrow: "icon_menuItem_subListArrow",
    campaignsFolder: "link_menuItem_campaignsFolder",
    campaignsList: "link_menuItem_campaignsList",
    hidePanelBtn: "btn_sidePanel_hide",
    userInfoContainer: "div_userInfo_container",
  },
  notifications: {
    modal: "modal_notification_container",
    popup: "popup_notification_container",
    title: "text_notification_title",
    message: "text_notification_message",
    closeBtn: "btn_notification_close",
  },
  confirmDialog: {
    modal: "modal_confirmDialog_container",
    title: "text_confirmDialog_title",
    message: "text_confirmDialog_message",
    approveBtn: "btn_confirmDialog_approve",
    cancelBtn: "btn_confirmDialog_cancel",
  },
  table: {
    definitionsTableBox: "div_definitionsTableBox_container",
    definitionsTable: "div_definitionsTable_container",
    definitionsTableRow: "div_definitionsTableRow_container",
  },
  datePicker: {
    popper: "popper_datePickerPopper_container",
  },
  confirmDlg: {
    container: "modal_confirmDialog_container",
    cancelBtn: "btn_confirmDialog_cancel",
    comment: "input_confirmDialogMessage_message",
  },
  campaignsList: {
    campaignsList: "div_campaignsList_container",
    campaignNameSearchField: "input_campaignName_textInput",
    campaignNameSearchBtn: "btn_campaignName_search",
    extFiltersBtn: "btn_extFilters_toggleShow",
    extFiltersContainer: "div_extFilters_container",
    extFilterInput: "input_extFilter_anyInput",
    extFiltersSearchBtn: "btn_extFilters_search",
    extFiltersClearBtn: "btn_extFilters_clear",
    campaignViewBtn: "btn_campaignAction_view",
    campaignEditBtn: "btn_campaignAction_edit",
    campaignDeactivateBtn: "btn_campaignAction_deactivate",
    createCampaignBtn: "btn_campaignAction_create",
  },
  campaignCreate: {
    campaignCreate: "div_campaignCreate_container",
    campaignCreateSaveBtn: "btn_campaignCreate_save",
    campaignCreateCancelBtn: "btn_campaignCreate_cancel",
  },
  campaignEdit: {
    campaignEdit: "div_campaignEdit_container",
    returnToList: "btn_campaignEdit_returnToList",
    saveCurrentChanges: "btn_campaignEdit_save",
    sendToApprove: "btn_campaignEdit_sendToApprove",
    confirmApproveDlg: "modal_campaignEditConfirmApprove_container",
    confirmApproveBtn: "btn_campaignEditConfirmApprove_approve",
    cancelApproveBtn: "btn_campaignEditConfirmApprove_cancel",
    cancel: "btn_campaignEdit_cancel",
    addScenarioBtn: "btn_scenario_add",
    editScenarioBtn: "btn_scenario_edit",
    deleteScenarioBtn: "btn_scenario_delete",
  },
  campaignView: {
    campaignView: "div_campaignView_container",
    campaignViewApproveBtn: "btn_campaignView_approve",
    campaignViewDeactivateBtn: "btn_campaignView_diactivate",
    campaignViewToEditBtn: "btn_campaignView_toEdit",
    campaignViewToListBtn: "btn_campaignView_toList",
  },
  scenariosCommon: {
    scenarioModalContainer: "modal_scenario_container",
    scenarioSaveBtn: "btn_scenario_save",
    scenarioCancelBtn: "btn_scenario_cancel",
    scnearioAttr: "input_scenarioAttr_anyInput",
  },
  campaignsCommon: {
    deactivateBtn: "btn_campaignDeactivate_send",
    needEditBtn: "btn_campaignNeedEdit_send",
    campaignAttrInput: "input_campaignAttr_anyInput",
  },
};
